### ISSUE TITLE
dokumentirati procedure za upravljanje uređajima

### ISSUE THREAD

**Issue by frnhr** [astrohr/dagor_tca#15]
All the steps needed to start shooting, and all the steps before going home.

Four checklists:
1. [x] [Startup procedure](https://github.com/astrohr/dagor_tca/wiki/Checklist:-Start)
2. [ ] Standard operation procedures
3. [ ] Shut down procedure
4. [ ] Emergency and troubleshooting procedures

**Comment by vedran-dobos** [comment]
May I suggest adding a yearly and/or monthly checkup document too.
This is when we can foresee some problems down the road or in the long run.
For example: check for worn parts, check connections (like solder points), nut tightening, etc.

**Comment by frnhr** [comment]
Good idea!

**Comment by frnhr** [comment]
Kamino closed and cloned this issue to [astrohr/dagor_wiki](https://github.com/astrohr/dagor_wiki/issues/4)
