### ISSUE TITLE
Mega (dome MCU) goes nuts when server isn't on

### ISSUE THREAD

**Issue by frnhr** [astrohr/dagor_tca#16]
Seems like USB extenders start to draw too much power. Unplugging USB resolves the problem.

 - [ ] Test possible voltage differences
 - [ ] Check how USB extenders behave in different power situations
 - [ ] Would a hub help?

**Comment by vedran-dobos** [comment]
Test again after fixing issue #24 - Arduino Mega (C1) was not properly (commonly) grounded.

**Comment by frnhr** [comment]
Still the same.

Looks like server draws power via USB when not powered on.

Putting a USB opto isolator between server and C1 (dome Arduino controller) fixes the problem, but brings up another one: Server doesn't recognize USB devices behind Opto_Isolator + Hub combo. It works fine with only one device, but not with both. My laptop recognizes all devices regardless. I believe a powered USB hub would solve the issue. The optoisolator *is* powered, but it is probably not very high quality.

For reference, check the [Overview diagram](https://github.com/astrohr/dagor_tca/wiki#overview).

![screen shot 2016-07-19 at 23 44 49](https://cloud.githubusercontent.com/assets/1173748/16967720/d6ee1dd2-4e0a-11e6-95dd-ba1f46f2f4ce.png)

**Comment by frnhr** [comment]
Also, the USB hub seems to be damaged, only two of four ports work (when tested directly with a laptop). I have replaced it with another USB hub, also not powered.

**Comment by frnhr** [comment]
Fixed by adding an opto isolator:

![img_1452](https://cloud.githubusercontent.com/assets/1173748/17025087/a49e8bf4-4f5a-11e6-81b2-9916e25e150f.jpg)


... and a powered USB hub:

![screenshot_21_07_16_15_49](https://cloud.githubusercontent.com/assets/1173748/17025120/d2f22218-4f5a-11e6-98fe-4eda314f455d.png)
