### ISSUE TITLE
Mega (dome MCU) triggers dome rotation randomly

### ISSUE THREAD

**Issue by frnhr** [astrohr/dagor_tca#17]
Possibly related to some ground issues, or possibly a blown internal pullup in Arduino.

 - [x] Plugin dongles in ports on dome enclosure
 - [x] Try without any dongles plugged in
 - [ ] Plug one dongle at a time
 - [ ] Check voltage levels in manual control boxes (those two yellow dongles with 4 buttons)
 - [ ] Add an external pullup resistor on Mega inputs
 - [ ] ... or change input pins (just for the test)

**Comment by frnhr** [comment]
##### Plugin dongles in ports on dome enclosure
No effect.

##### Try without any dongles plugged in
No random rotations, unless Mega is touched with a finger. So almost no effect...

**Comment by vedran-dobos** [comment]
Test again after fixing issue #24 - Arduino Mega (C1) was not properly (commonly) grounded.

**Comment by frnhr** [comment]
It was the ground...
