### ISSUE TITLE
Power regulators in dome encl. are too hot

### ISSUE THREAD

**Issue by frnhr** [astrohr/dagor_tca#24]
20-10-5-0 V regulators are too hot.
- [x] What draws too much current - **Arduino Mega (C1) was not properly (commonly) grounded.**
- [ ] Do we need a better circuit?

**Comment by vedran-dobos** [comment]
Just for testing purposes the 5V rail is bypassed, and it actually fixed the voltage problems.

![img_20160613_152217](https://cloud.githubusercontent.com/assets/19259909/16049709/09a65398-3259-11e6-9989-9910b16b2194.jpg)
![img_20160613_152234](https://cloud.githubusercontent.com/assets/19259909/16049708/099b78e2-3259-11e6-952c-03d991f09876.jpg)

The 20V, 10V, and 5V rails are now within a few % error.
![img_20160613_152417](https://cloud.githubusercontent.com/assets/19259909/16049864/a23bcd68-3259-11e6-92e0-41a205af7d2a.jpg)
![img_20160613_152312](https://cloud.githubusercontent.com/assets/19259909/16049865/a23c4ce8-3259-11e6-87a4-21f7dac8d196.jpg)
(20V rail not shown, but is also OK)

There might be problems within the cable leading to the dome encoder and position switches.
I will rework all the connections and identify the culprit (encoder/switches/something_else).

**Comment by vedran-dobos** [comment]
Found the issue!! :satisfied:
Arduino Mega (C1) was not properly (commonly) grounded.

Added a ground wire, and most of the problems went away. It could be done more nicely, but works anyway.

![img_20160620_160358](https://cloud.githubusercontent.com/assets/19259909/16208759/f8aa7eae-3733-11e6-8eb1-d2100c88bc40.jpg)

Output is now stable:
5V:
![img_20160620_160654](https://cloud.githubusercontent.com/assets/19259909/16208781/18a17e74-3734-11e6-85a9-6389788a4e15.jpg)

10V:
![img_20160620_160703](https://cloud.githubusercontent.com/assets/19259909/16208780/18a092de-3734-11e6-9813-e2ec75f83052.jpg)
20V:
![img_20160620_160713](https://cloud.githubusercontent.com/assets/19259909/16208782/18a9a1a8-3734-11e6-9aeb-a65ca2defcbb.jpg)

Still, the analog inputs are not working properly, too small resistance measured, resulting in increased power consumption:
A4 = 175 Ohm
A5 = 142 Ohm
A6 = 290 KOhm
All other analog inputs ~7 MOhm

- [ ] Use different analog inputs or switch to digital inputs (if possible)

Other fixes done while debugging:

- Changed C1 power adapter setting to 4.5V, as in reality it is delivering 7.7V at this setting (under load). Setting on 7.5V delivered above 11V, and caused unnecessary heating of the LM7805 on the C1.
![img_20160620_160558](https://cloud.githubusercontent.com/assets/19259909/16209045/72191704-3735-11e6-9853-180b2ea6a7e7.jpg)

- Simplified connection to dome sensor cable
![img_20160620_125900](https://cloud.githubusercontent.com/assets/19259909/16209266/82871a90-3736-11e6-94c7-92e19c36175b.jpg)

- Split sensor cable for dome rotation encoder/fixed switches in an electric box
![img_20160620_151220](https://cloud.githubusercontent.com/assets/19259909/16209283/95f1c328-3736-11e6-8ab3-46f4e6359171.jpg)
![img_20160620_151232](https://cloud.githubusercontent.com/assets/19259909/16209293/a773be4e-3736-11e6-97a6-3f48ba77991e.jpg)
Note: pinout changed after photo taken.

- Redone connection to encoder with nice heat-shrink tubing :heart_eyes:
![img_20160620_151259](https://cloud.githubusercontent.com/assets/19259909/16209345/e060b464-3736-11e6-9e17-3eab221308ab.jpg)

**Comment by frnhr** [comment]
Nice work!

Re common ground - makes perfect sense! Mega ("C1") used to be powered by the common 5V output (and grounded there too). For _reasons_ (keeping the heat down, I guess) we added the extra switching power source, but no-one thought of grounding its output :)

Re analog inputs - that would imply faulty (i.e. burned) Atmega chip, since normally impedance on all inputs is very high, of course. BTW datasheet actually says it should be 100MΩ, but that's probably not realistic, as discussed here: http://electronics.stackexchange.com/a/67173/19509

We can't switch to digital inputs without loosing the two-step speed control (well, we _could_, with a few voltage comparators... but let's keep it simple). We have another Arduino Mega board, so we can test how it behaves. And we can switch to using the other analogue inputs. And buy a new Mega...

**Comment by vedran-dobos** [comment]
Re common ground: Took a whole day of figuring out how to connect one simple wire in the end :sweat_smile:

Re analog inputs: The A4-6 pins are used for the dome rotation switches, not for the speed control...?
Anyhow, let's change the A inputs and change the code to see how it behaves.

- [ ] Test position switches and dome encoder through software to ensure cabling was re-done correctly

**Comment by frnhr** [comment]
Ah, those ADC inputs, I see.

Actually, adding 3 x 5kΩ in front of those pins would most likely solve our problem.
At the same time, the Mega shield needs to be made as a PCB (it is currently made on a proto-shield). I'll make a new issue for that, so feel free to close this one if there is nothing else to be done.
