### ISSUE TITLE
Doors Nano (MCU for controlling dome doors) needs signals from limit switches

### ISSUE THREAD

**Issue by frnhr** [astrohr/dagor_tca#26]
Max voltage for Arduino: 5V!

Range for a logical "1": 3V - 5V
Range for logical "0": 0V - 1.5V
(a simple"voltage divider" in 20k - 100k range should be ok)

 - [x] ~~What is the impedance of digital input or ATMega328?~~ (not relevant, relay contacts)

**Comment by vedran-dobos** [comment]
Cabling done. Ends in the control box.
It's an independent Normally Open circuit until the switches engage, at that point the circuit closes.

Used the 2 pairs of signal wires:
-blue/white-blue for "open" switch
-green/white-green for "closed" switch

**Comment by vedran-dobos** [comment]
Connected MCU C3 with doors sensors.
Pin D4 - Doors closed
Pin D3 - Doors opened

Code here on Github shiws using analog inputs?
Is this old code, or some other error?
