### ISSUE TITLE
Fans for primary mirror

### ISSUE THREAD

**Issue by frnhr** [astrohr/dagor_tca#37]
4 fans should be placed on the base, on plastic caps behind primary mirror.

 - [x] mount
 - [x] connect power (12 V for the fans, Arduino should be powered via USB)
 - [x] install relays and arduino control, similar to existing lights switch
 - [x] code CLI module
 - [x] code API module
 - [x] code ASCOM module

**Comment by vedran-dobos** [comment]
A few questions:

- what size should the fans be? could standard 12cm work?
- do fans need to be mechanically decoupled (anti-vibration mounting)?
- is speed control necessary? is it dependent on temperature difference?
- is individual speed control necessary (multi zone temp control)?
- is noise an issue?

**Comment by frnhr** [comment]
Final conclusions about the fans (after multiple emails and in person talks)...

 * only 3 fans
 * blowing in
 * must have dust filters
 * we already have the fans, 12 cm, scavenged from a server rack, 6 of them
 * we have 5 dust filters
 * anti-vibration mounting is preferable
 * no need for speed reduction
 * don't care about noise

**Comment by frnhr** [comment]
Temporarily mounted:
![img_1585](https://cloud.githubusercontent.com/assets/1173748/17577682/1e0db4b6-5f81-11e6-9748-12717a09e241.jpg)

Connected to server, CLI working fine. API also tested (on the bench) and working. Next step: test ACOM.

**Comment by nkatanic** [comment]
ASCOM driver tested and working.

**Comment by frnhr** [comment]
Measures for caps:

Outer diameter: 205 mm
Inner diameter: 115 mm
Holes distance: 104.5 mm
Holes diagonal distance: 147.8 mm
Holes: M4 thread
Place thickness: >2mm, not important

![kape_za_ventilatore](https://cloud.githubusercontent.com/assets/1173748/17608131/9d5fec6c-602a-11e6-8f9a-662a156215e4.png)

**Comment by vedran-dobos** [comment]
May I suggest taking into account rubber grommets for noise/vibration reduction into the design?

![img_20160812_012212](https://cloud.githubusercontent.com/assets/19259909/17608263/8f20e54c-602b-11e6-85fc-5777841925ad.jpg)

I have a few lots, and we can select the appropriate ones.

**Comment by frnhr** [comment]
Can we use these and still not have gaps between fan and cap plate?
