### ISSUE TITLE
Labels! Moar labels!!

### ISSUE THREAD

**Issue by frnhr** [astrohr/dagor_tca#39]
Who printed these?!
![screenshot_30_05_16_19_02](https://cloud.githubusercontent.com/assets/1173748/15654993/142f9caa-2699-11e6-9801-fc9a452160c1.png)

Why only these?! We need labels! Moar labels!
![moar_meme_generator_-_imgflip](https://cloud.githubusercontent.com/assets/1173748/15655054/a816229a-2699-11e6-8dfb-f5ea1afb90d9.png)

Can we print tiny graphics on labels?

**Comment by vedran-dobos** [comment]
They must have printed themselves! :wink:

See page 14 of manual for graphics:
http://download.dymo.com/dymo/user-guides/LetraTag/LT100H/UG/LT100H_UserGuide_en-US.pdf

**Comment by vedran-dobos** [comment]
These things keep reproducing by themselves!! We can't stop them anymore!!

![img_20160531_161141](https://cloud.githubusercontent.com/assets/19259909/15689044/5fb56b02-277d-11e6-9378-3cf72cbba194.jpg)

**Comment by frnhr** [comment]
### Dome fuse enclosure

 - [ ] Lower switch should be labeled "DIRECT CONTROL" instead of "ELECTRONIC CONTROL"
 - [ ] Let's change "CLOCKWISE" to "UP" and "DOWN", following the [Right-hand rule](https://en.wikipedia.org/wiki/Right-hand_rule#Rotation)

### Telescope drives enclosure

 - [ ] "MAIN POWER"
 - [ ] "DRIVES POWER"
 - [ ] "DO NOT SWITCH WHILE TELESCOPE IS MOVING!"

### Other

 - [ ] Let's label switches for dome doors with "OPEN" and "CLOSE"
 - [ ] Maybe laben enclosures themselves? Like "TELESCOPE DRIVES ENCLOSURE"...

### MOAR!!!

**Comment by frnhr** [comment]
- [ ] Camera, On, Off

**Comment by frnhr** [comment]
- [ ] Focuser On, Off

**Comment by frnhr** [comment]
- [ ] Various labels on focuser enclosure (the black one on the spider)
