### ISSUE TITLE
harveraj / estetika

### ISSUE THREAD

**Issue by dario-zubovic** [astrohr/dagor_tca#4]
- [x]  provuci kabel do emergency stopa u kontrolnoj
- [ ]  kanalice za kabele i kutija za USB hub
- [ ]  srediti do kraja kutiju za kupolu (PCB za regulatore napona, organizirati kabele...)
- [x]  spojiti switcheve na vratima kupole na arduino na kupoli

**Comment by vedran-dobos** [comment]
- ~~provuci kabel do emergency stopa u kontrolnoj~~ __PARTIALLY DONE__
- kanalice za kabele i kutija za USB hub
- srediti do kraja kutiju za kupolu (PCB za regulatore napona, organizirati kabele...)
- ~~spojiti switcheve na vratima kupole na arduino na kupoli~~ __DONE__
