### ISSUE TITLE
Emergency stop in control room

### ISSUE THREAD

**Issue by vedran-dobos** [astrohr/dagor_tca#40]
Extracted from issue [#4](https://github.com/astrohr/dagor_tca/issues/4)

Emergency stop button moved to a more convenient location (for cabling) and wired. Old holes in the wall are filled with plaster/gipsum.
Used orange/white-orange cores on a Normally Closed terminal. Roll of cable left under the table.

Left to do:
- [x] cut cable to length
- [x] connect cable to emergency loop in control cabinet

WIP:

![img_20160531_154616](https://cloud.githubusercontent.com/assets/19259909/15688740/c6e02152-277b-11e6-81b6-1fa81bfb7ae3.jpg)

![img_20160531_193643](https://cloud.githubusercontent.com/assets/19259909/15688816/382b6a9c-277c-11e6-8d7b-6c3447b2be8d.jpg)

![img_20160531_193749](https://cloud.githubusercontent.com/assets/19259909/15688742/c6e406a0-277b-11e6-8ae3-ce63d3b7a0f0.jpg)

Final result:

![img_20160531_194724](https://cloud.githubusercontent.com/assets/19259909/15688831/5340abc6-277c-11e6-9f65-96b5813dc53c.jpg)

**Comment by frnhr** [comment]
Connected.
