### ISSUE TITLE
Check what wires are used by USB extenders

### ISSUE THREAD

**Issue by frnhr** [astrohr/dagor_tca#47]
Maybe we have available wires for power.

**Comment by vedran-dobos** [comment]
Highly unlikely.

Most probably every USB wire is fed through a twisted pair on the ethernet cable, or the data+/- pair is using one twisted pair, and the other 6 wires are V+/-.

Worth checking though :smile:

**Comment by frnhr** [comment]
Yeah, probably.

Ideally, though, we would have some free wires, and those would be the same wires that are used by PoE standard :)

**Comment by frnhr** [comment]
Power (5 V) is connected to line `7` and `8`

Ground is connected to lines `3`, `4`, `5` and `6`.

We can make REVERSED POLARITY PoE. Not sure if we _should_... But it's an option.

Here is the USUAL PoE pinout:

![google_image_result_for_http___lh6_ggpht_com_-zjnus407bvw_un-ivwp_3ci_aaaaaaaadkm_0aqcy3zseww_image_thumb_25255b1_25255d_png_imgmax_800](https://cloud.githubusercontent.com/assets/1173748/17024765/6a713aa4-4f59-11e6-8897-b9bf64d414d2.png)


There are [other standards](http://pinoutsguide.com/Net/poe_pinout.shtml), naturally...

I'm closing this issue for now. We will reopen if need PoE.


BTW, we already have a pair of PoE injectors, unused:
![screen shot 2016-07-21 at 15 32 49](https://cloud.githubusercontent.com/assets/1173748/17024501/7160f5a8-4f58-11e6-9958-e05fe910a3b6.png)
