### ISSUE TITLE
calculating/interpolating dome position to match with telescope

### ISSUE THREAD

**Issue by frnhr** [astrohr/dagor_tca#6]

**Comment by vedran-dobos** [comment]
Running a neural network on the collected data did not yield satisfactory results.
More manual input (learning) data might be needed, or a different approach altogether.

Or we can try to mathematically calculate the position through a mysterious formula :smile: 

![dome_position_interpolated](https://cloud.githubusercontent.com/assets/19259909/15643754/55bfbcee-264f-11e6-8b2d-de433ed8393e.png)

[altazazch.txt](https://github.com/astrohr/dagor_tca/files/289131/altazazch.txt)

**Comment by frnhr** [comment]
Best way to plot this data is in cylindrical coordinates, with telescope position on polar plane (azimuth on θ, 90°-altitude on r) and dome azimuth on z axes.

Probably won't make a difference in the NN result, just putting it here for future reference.
