### ISSUE TITLE
Dome battery is empty

### ISSUE THREAD

**Issue by frnhr** [astrohr/dagor_tca#66]
Either the battery has died or the charger is no longer working. There is no power in the battery and the charger is not flashing when connected.

In the meantime:
![img_1227](https://cloud.githubusercontent.com/assets/1173748/17837222/11295ad2-67ad-11e6-9bd7-863c38f2c411.jpg)

**Comment by vedran-dobos** [comment]
Changed 7A5 fuse in fuse box near the battery.
